#!/usr/bin/env python3
"""
Author : Tanveer Ahmed
Date   : 2024-07-21
Purpose: Create the core logic for crow's Nest
"""

import argparse


# --------------------------------------------------
def get_args():
    """Get command-line arguments"""

    parser = argparse.ArgumentParser(
        description='Create the core logic for crows Nest',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('Object',
                        metavar='Object',
                        help='Pass the object')

    return parser.parse_args()

# --------------------------------------------------
def main():
    """Make a jazz noise here"""

    args = get_args()
    Object = args.Object
    article = "an" if Object[0].lower() in 'aeiou'  else "a"
    print('Ahoy! Captain {} {} in off the ladder board'.format(article,Object))
    

# --------------------------------------------------
if __name__ == '__main__':
    main()
